#version: "3"
#services:
#  postgress:
#    image: postgres:latest
#    restart: always
#    network_mode: bridge
#    container_name: postgress
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
#    expose:
#      - 5434
#    ports:
#      - "5434:5432"
#    environment:
#      - POSTGRES_PASSWORD=uwafe5983
#      - POSTGRES_USER=postgres
#      - POSTGRES_DB=terrondb
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#
##  postgresqldb:
##    image: 'postgres:13.1-alpine'
##    container_name: postgresqldb
##    ports:
##      - "5432:5432"
##    environment:
##      - POSTGRES_USER=postgres
##      - POSTGRES_PASSWORD=uwafe5983
#
#  app:
#    image: terronapi
#    network_mode: bridge
#    container_name: terronapi
#    expose:
#      - 9000
#    ports:
#      - "9000:9000"
#    depends_on:
#      - postgress
#    links:
#      - postgress
#    environment:
#      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
#      - POSTGRES_PASSWORD=uwafe5983
#      - POSTGRES_USER=postgres
#      - POSTGRES_DB=terrondb
#      - POSTGRES_URL=jdbc:postgresql://127.0.0.1:5434/terrondb
#
#
#volumes:
#  postgres-data: