
spring.jpa.database=POSTGRESQL
spring.datasource.platform=postgres
spring.datasource.url=jdbc:postgresql://localhost:5435/terron_db
#spring.datasource.url=jdbc:postgresql://172.17.0.2:5432/terrondb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=username
#spring.datasource.username=postgres
#spring.datasource.password=password12345
spring.datasource.password=password
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

server.port=8080
#spring.mail.host = localhost
#spring.mail.port = 1025
#spring.mail.username = hello
#spring.mail.password = hello
#spring.mail.properties.mail.smtp.ssl.trust = "*"
#spring.mail.properties.mail.smtp.starttls.enable = true
#spring.mail.properties.mail.smtp.auth = true
#spring.mail.properties.mail.smtp.connectiontimeout = 5000
#spring.mail.properties.mail.smtp.timeout = 5000
#spring.mail.properties.mail.smtp.writetimeout = 5000